package backend.utils;

class DrawUtil {
    public static function addRect(spr:ASprite, rect:Rectangle, color:AColor):ASprite {
        spr.graphics.beginFill(color.rgb, color.a);
            spr.graphics.drawRect(rect.x, rect.y, rect.width, rect.height);
        spr.graphics.endFill();
        return spr;
    }

    //TODO: support scaling on the graphic.
    public static function drawIcon(spr:ASprite, icon:String, thickness:Int, outlineColor:AColor, fillColor:AColor):ASprite {
        if(!Reflect.hasField(ADrawableIcons, icon)) {
            trace('Unrecognized icon $icon, aborting!');
            return spr;
        }
        if(!(spr is backend.ui.ACheckBox)) spr.reRender(); //reRender graphic so that the icon is cleared. but only if it isnt a checkbox.
        spr.graphics.lineStyle(thickness, outlineColor.rgb??AColor.BLACK.rgb, outlineColor.a??1.0); //set line style
            spr.graphics.beginFill(fillColor.rgb, fillColor.a);
                for(command in (Reflect.field(ADrawableIcons, icon):Array<ADrawableIconCommand>)) {
                    switch(command.t) {
                        case MOVE: spr.graphics.moveTo(command.a.x, command.a.y);
                        case LINE: spr.graphics.lineTo(command.a.x, command.a.y);
                    }
                }
            spr.graphics.endFill();
        spr.graphics.lineStyle(null, 0, 1); //reset linestyle to default.
        return spr;
    }
}

enum ADrawableIconCommandType {MOVE; LINE;}
typedef ADrawableIconCommand = {t:ADrawableIconCommandType,a:{x:Float, y:Float}}; 
/**
    do **NOT** make these manually.
    use the utility.
    Abode\Tools\ADrawableIconGen.html in your browser.
 */
class ADrawableIcons {
    public static final SOUND:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:7, y:5}},
        {t:LINE, a:{x:7, y:14}},
        {t:LINE, a:{x:3, y:11}},
        {t:LINE, a:{x:3, y:8}},
        {t:LINE, a:{x:7, y:5}},
        {t:MOVE, a:{x:9, y:3}},
        {t:LINE, a:{x:11, y:4}},
        {t:LINE, a:{x:12, y:7}},
        {t:LINE, a:{x:12, y:11}},
        {t:LINE, a:{x:11, y:14}},
        {t:LINE, a:{x:9, y:16}},
        {t:LINE, a:{x:10, y:14}},
        {t:LINE, a:{x:11, y:11}},
        {t:LINE, a:{x:11, y:7}},
        {t:LINE, a:{x:10, y:4}},
        {t:LINE, a:{x:9, y:3}},
        {t:MOVE, a:{x:12, y:1}},
        {t:LINE, a:{x:14, y:2}},
        {t:LINE, a:{x:16, y:6}},
        {t:LINE, a:{x:16, y:12}},
        {t:LINE, a:{x:15, y:15}},
        {t:LINE, a:{x:12, y:17}},
        {t:LINE, a:{x:14, y:15}},
        {t:LINE, a:{x:15, y:12}},
        {t:LINE, a:{x:15, y:6}},
        {t:LINE, a:{x:13, y:2}},
        {t:LINE, a:{x:12, y:1}},
    ];
    public static final MUTE:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:7, y:5}},
        {t:LINE, a:{x:7, y:14}},
        {t:LINE, a:{x:3, y:11}},
        {t:LINE, a:{x:3, y:8}},
        {t:LINE, a:{x:7, y:5}},
        {t:MOVE, a:{x:9, y:3}},
        {t:LINE, a:{x:11, y:4}},
        {t:LINE, a:{x:12, y:7}},
        {t:LINE, a:{x:12, y:11}},
        {t:LINE, a:{x:11, y:14}},
        {t:LINE, a:{x:9, y:16}},
        {t:LINE, a:{x:10, y:14}},
        {t:LINE, a:{x:11, y:11}},
        {t:LINE, a:{x:11, y:7}},
        {t:LINE, a:{x:10, y:4}},
        {t:LINE, a:{x:9, y:3}},
        {t:MOVE, a:{x:12, y:1}},
        {t:LINE, a:{x:14, y:2}},
        {t:LINE, a:{x:16, y:6}},
        {t:LINE, a:{x:16, y:12}},
        {t:LINE, a:{x:15, y:15}},
        {t:LINE, a:{x:12, y:17}},
        {t:LINE, a:{x:14, y:15}},
        {t:LINE, a:{x:15, y:12}},
        {t:LINE, a:{x:15, y:6}},
        {t:LINE, a:{x:13, y:2}},
        {t:LINE, a:{x:12, y:1}},
        {t:MOVE, a:{x:0, y:20}},
        {t:LINE, a:{x:1, y:20}},
        {t:LINE, a:{x:20, y:0}},
        {t:LINE, a:{x:19, y:0}},
        {t:LINE, a:{x:0, y:20}},
        {t:MOVE, a:{x:0, y:0}},
        {t:LINE, a:{x:1, y:0}},
        {t:LINE, a:{x:20, y:20}},
        {t:LINE, a:{x:19, y:20}},
        {t:LINE, a:{x:0, y:0}},
    ];

    public static final WIN_CLOSE:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:3, y:3}},
        {t:LINE, a:{x:16, y:17}},
        {t:LINE, a:{x:17, y:17}},
        {t:LINE, a:{x:4, y:3}},
        {t:LINE, a:{x:3, y:3}},
        {t:MOVE, a:{x:17, y:3}},
        {t:LINE, a:{x:4, y:17}},
        {t:LINE, a:{x:3, y:17}},
        {t:LINE, a:{x:16, y:3}},
        {t:LINE, a:{x:17, y:3}},
    ];
    public static final WIN_MAX:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:3, y:3}},
        {t:LINE, a:{x:3, y:3}},
        {t:LINE, a:{x:17, y:3}},
        {t:LINE, a:{x:17, y:17}},
        {t:LINE, a:{x:3, y:17}},
        {t:LINE, a:{x:3, y:3}},
    ];
    public static final WIN_MIN:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:3, y:7}},
        {t:LINE, a:{x:3, y:7}},
        {t:LINE, a:{x:17, y:7}},
        {t:LINE, a:{x:17, y:14}},
        {t:LINE, a:{x:3, y:14}},
        {t:LINE, a:{x:3, y:7}},
    ];

    public static final FILE_FLASH:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:15, y:67}},
        {t:LINE, a:{x:60, y:67}},
        {t:LINE, a:{x:60, y:29}},
        {t:LINE, a:{x:43, y:8}},
        {t:LINE, a:{x:15, y:8}},
        {t:LINE, a:{x:15, y:67}},
        {t:MOVE, a:{x:17, y:55}},
        {t:LINE, a:{x:21, y:55}},
        {t:LINE, a:{x:21, y:38}},
        {t:LINE, a:{x:26, y:38}},
        {t:LINE, a:{x:26, y:35}},
        {t:LINE, a:{x:21, y:35}},
        {t:LINE, a:{x:21, y:31}},
        {t:LINE, a:{x:30, y:31}},
        {t:LINE, a:{x:30, y:27}},
        {t:LINE, a:{x:17, y:27}},
        {t:LINE, a:{x:17, y:55}},
        {t:MOVE, a:{x:32, y:56}},
        {t:LINE, a:{x:42, y:56}},
        {t:LINE, a:{x:42, y:53}},
        {t:LINE, a:{x:36, y:53}},
        {t:LINE, a:{x:36, y:27}},
        {t:LINE, a:{x:32, y:27}},
        {t:LINE, a:{x:32, y:56}},
        {t:MOVE, a:{x:44, y:56}},
        {t:LINE, a:{x:50, y:26}},
        {t:LINE, a:{x:56, y:56}},
        {t:MOVE, a:{x:48, y:45}},
        {t:LINE, a:{x:52, y:45}},
        {t:LINE, a:{x:50, y:37}},
        {t:MOVE, a:{x:54, y:56}},
        {t:LINE, a:{x:52, y:47}},
        {t:LINE, a:{x:48, y:47}},
        {t:LINE, a:{x:46, y:56}},
        {t:MOVE, a:{x:56, y:56}},
        {t:LINE, a:{x:54, y:56}},
        {t:MOVE, a:{x:46, y:56}},
        {t:LINE, a:{x:44, y:56}},
        {t:MOVE, a:{x:50, y:37}},
        {t:LINE, a:{x:48, y:45}},
        {t:MOVE, a:{x:44, y:56}},
        {t:LINE, a:{x:50, y:26}},
        {t:LINE, a:{x:56, y:56}},
        {t:MOVE, a:{x:54, y:56}},
        {t:LINE, a:{x:52, y:47}},
        {t:LINE, a:{x:48, y:47}},
        {t:LINE, a:{x:46, y:56}},
        {t:MOVE, a:{x:48, y:45}},
        {t:LINE, a:{x:50, y:37}},
        {t:LINE, a:{x:52, y:45}},
        {t:MOVE, a:{x:17, y:55}},
        {t:LINE, a:{x:21, y:55}},
        {t:LINE, a:{x:21, y:38}},
        {t:LINE, a:{x:26, y:38}},
        {t:LINE, a:{x:26, y:35}},
        {t:LINE, a:{x:21, y:35}},
        {t:LINE, a:{x:21, y:31}},
        {t:LINE, a:{x:30, y:31}},
        {t:LINE, a:{x:30, y:27}},
        {t:LINE, a:{x:17, y:27}},
        {t:LINE, a:{x:17, y:55}},
        {t:MOVE, a:{x:32, y:56}},
        {t:LINE, a:{x:42, y:56}},
        {t:LINE, a:{x:42, y:53}},
        {t:LINE, a:{x:36, y:53}},
        {t:LINE, a:{x:36, y:27}},
        {t:LINE, a:{x:32, y:27}},
        {t:LINE, a:{x:32, y:56}},
    ];
    public static final FILE_ABODEPROJECTFORMAT:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:15, y:67}},
        {t:LINE, a:{x:60, y:67}},
        {t:LINE, a:{x:60, y:29}},
        {t:LINE, a:{x:43, y:8}},
        {t:LINE, a:{x:15, y:8}},
        {t:LINE, a:{x:15, y:67}},
        {t:MOVE, a:{x:17, y:56}},
        {t:LINE, a:{x:20, y:56}},
        {t:LINE, a:{x:24, y:35}},
        {t:LINE, a:{x:27, y:56}},
        {t:LINE, a:{x:29, y:56}},
        {t:LINE, a:{x:24, y:31}},
        {t:LINE, a:{x:17, y:56}},
        {t:MOVE, a:{x:20, y:56}},
        {t:LINE, a:{x:27, y:56}},
        {t:LINE, a:{x:26, y:49}},
        {t:LINE, a:{x:22, y:46}},
        {t:MOVE, a:{x:30, y:56}},
        {t:LINE, a:{x:30, y:31}},
        {t:LINE, a:{x:40, y:31}},
        {t:LINE, a:{x:43, y:32}},
        {t:LINE, a:{x:45, y:35}},
        {t:LINE, a:{x:45, y:37}},
        {t:LINE, a:{x:43, y:40}},
        {t:LINE, a:{x:40, y:42}},
        {t:LINE, a:{x:33, y:42}},
        {t:LINE, a:{x:33, y:56}},
        {t:LINE, a:{x:30, y:56}},
        {t:MOVE, a:{x:33, y:35}},
        {t:LINE, a:{x:33, y:39}},
        {t:LINE, a:{x:37, y:39}},
        {t:LINE, a:{x:41, y:38}},
        {t:LINE, a:{x:41, y:36}},
        {t:LINE, a:{x:37, y:35}},
        {t:LINE, a:{x:33, y:35}},
        {t:MOVE, a:{x:46, y:56}},
        {t:LINE, a:{x:46, y:31}},
        {t:LINE, a:{x:56, y:31}},
        {t:LINE, a:{x:56, y:36}},
        {t:LINE, a:{x:49, y:36}},
        {t:LINE, a:{x:49, y:39}},
        {t:LINE, a:{x:52, y:39}},
        {t:LINE, a:{x:52, y:42}},
        {t:LINE, a:{x:49, y:42}},
        {t:LINE, a:{x:49, y:56}},
        {t:LINE, a:{x:46, y:56}},
        {t:MOVE, a:{x:30, y:56}},
        {t:LINE, a:{x:33, y:56}},
        {t:LINE, a:{x:33, y:42}},
        {t:LINE, a:{x:40, y:42}},
        {t:LINE, a:{x:43, y:40}},
        {t:LINE, a:{x:45, y:37}},
        {t:LINE, a:{x:45, y:35}},
        {t:LINE, a:{x:43, y:32}},
        {t:LINE, a:{x:40, y:31}},
        {t:LINE, a:{x:30, y:31}},
        {t:MOVE, a:{x:49, y:56}},
        {t:LINE, a:{x:49, y:42}},
        {t:LINE, a:{x:52, y:42}},
        {t:LINE, a:{x:52, y:39}},
        {t:LINE, a:{x:49, y:39}},
        {t:LINE, a:{x:49, y:36}},
        {t:LINE, a:{x:56, y:36}},
        {t:LINE, a:{x:56, y:31}},
        {t:LINE, a:{x:46, y:31}},
        {t:LINE, a:{x:46, y:56}},
        {t:MOVE, a:{x:33, y:39}},
        {t:LINE, a:{x:37, y:39}},
        {t:LINE, a:{x:41, y:38}},
        {t:LINE, a:{x:41, y:36}},
        {t:LINE, a:{x:37, y:35}},
        {t:LINE, a:{x:33, y:35}},
        {t:LINE, a:{x:33, y:39}},
        {t:MOVE, a:{x:17, y:56}},
        {t:LINE, a:{x:24, y:31}},
        {t:LINE, a:{x:29, y:56}},
        {t:LINE, a:{x:27, y:56}},
        {t:LINE, a:{x:24, y:35}},
        {t:LINE, a:{x:20, y:56}},
        {t:LINE, a:{x:17, y:56}},
        {t:MOVE, a:{x:20, y:56}},
        {t:LINE, a:{x:22, y:46}},
        {t:MOVE, a:{x:20, y:56}},
        {t:LINE, a:{x:27, y:56}},
        {t:LINE, a:{x:26, y:49}},
        {t:LINE, a:{x:22, y:46}},
        {t:LINE, a:{x:20, y:56}},
    ];
    public static final UICHECK:Array<ADrawableIconCommand> = [
        {t:MOVE, a:{x:5, y:10}},
        {t:LINE, a:{x:10, y:14}},
        {t:LINE, a:{x:20, y:0}},
        {t:LINE, a:{x:19, y:0}},
        {t:LINE, a:{x:10, y:12}},
        {t:LINE, a:{x:4, y:8}},
        {t:LINE, a:{x:5, y:10}}
    ];
}